@startuml RDCU redémarrerJeu
title RDCU pour redémarrerJeu
participant " :JeuDeDes" as D
participant "joueurs: \n Map<String, Joueur>" as J
 
-> D : redemarrerJeu()
note right
   selon Contrôleur
   (JeuDeDes est
   l'objet racine)
end note
D -> J : clear()
note right
   selon Expert
end note
@enduml
